name: CI/CD workflow to read hello.txt

on:
    push:
        branches: 
            - main

jobs:
    Read_hello_File:
        runs-on: ubuntu-latest

        steps:
            - name: Git Clone (Checkout Repository)
              uses: actions/checkout@v3

            - name: Verify hello.txt exists
              run: |
                if [ -f hello.txt ]; then
                    echo "hello.txt found successfully."
                else
                    echo "hello.txt not found unfortunately."
                    exit 1
                fi

            - name: Display contents of hello.txt
              run: |
                echo "-----------Contents of hello.txt-----------"
                cat hello.txt
                echo "-------------------------------------------"